#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
title: The Dream Developer
description: Hi, I am Ishan Roy Chowdhury and this is my quest to become the developer of my dreams.
theme: minima
