theme: minima
title: The Dream Developer
description: Hi, I am Ishan Roy Chowdhury and this is my quest to become the developer of my dreams.
author:
  name: IshanRoyChowdhury
  email: ishan.r.chowdhury@gmail.com
