remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Dream Developer
description: Hi, I am Ishan Roy Chowdhury and welcome to my webpage.
show_downloads: false
google_analytics:
